### PR TITLE
Cargo.toml: Add repository

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by mpizenberg** [comment]
Hi, I’m just wondering what is the purpose of this PR. It’s fine to add the link to the repo, but why though? It’s not like its needed.
PS, this project is not part of hacktoberfest.

**Comment by jayvdb** [comment]
I am looking through crates.io for tile services, and this one didnt have a repository link.  So I had to go find it.

Ah hacktoberfest .. I havent done that for a while.  My shirt draw is full.

**Comment by mpizenberg** [comment]
Ah, makes sense. Sorry I’m suspicious in october XD

**Comment by mpizenberg** [comment]
Meh, CI failing, but it’s not worth fixing IMO. Thanks!

**Pull request merged**
